import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";

// Bootstrap CSS
import 'bootstrap/dist/css/bootstrap.min.css';
// Bootstrap Icons CSS
import 'bootstrap-icons/font/bootstrap-icons.css';
// Font Awesome Configuration
import '../lib/fontawesome';

import "./globals.css";
const inter = Inter({ subsets: ['latin'] });
import QueryProvider from "../lib/QueryProvider";
import HeaderPage from "../global-components/header/header";
import FooterPage from "../global-components/footer/footer";
import HydrationSafeBody from "@src/global-components/HydrationSafeBody";
import { ThemeProvider } from "../context/ThemeContext";
import FormioThemeInitializer from "../components/FormioThemeInitializer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={inter.className}
      >
        <QueryProvider>
          <HydrationSafeBody>
            <HeaderPage />
                {children}
            <FooterPage />
          </HydrationSafeBody>
        </QueryProvider>
      </body>
    </html>
  );
}
